Added Integration Foregoing 1.12 CraftTweaker documentation
CraftTweaker/CraftTweaker-Documentation pull request #394
Opened 2021-02-11 17:59 UTC by JackyyTV

- Added documentation for Washing Factory, Fermentation Station and Fluid Sieving Machine.

2021-02-11 18:12 UTC, jaredlll08 requested changes

2021-02-11 18:12 UTC, jaredlll08 commented on docs/Mods/Integration_Foregoing/FermentationStation.md
> +FermentationStation.add(ILiquidStack fluidInput, ILiquidStack fluidOutput);
Put this in a comment please, just so people know that it isn't a line that is actually meant to work

2021-02-11 18:12 UTC, jaredlll08 commented on docs/Mods/Integration_Foregoing/FermentationStation.md
> +FermentationStation.remove(ILiquidStack fluidInput);
Put this in a comment please, just so people know that it isn't a line that is actually meant to work

2021-02-11 18:12 UTC, jaredlll08 commented on docs/Mods/Integration_Foregoing/FluidSievingMachine.md
> +FluidSievingMachine.add(ILiquidStack fluidInput, IItemStack itemOutput, IItemStack sieveItemInput);
Put this in a comment please, just so people know that it isn't a line that is actually meant to work

2021-02-11 18:12 UTC, jaredlll08 commented on docs/Mods/Integration_Foregoing/FluidSievingMachine.md
> +FluidSievingMachine.remove(IItemStack itemOutput);
Put this in a comment please, just so people know that it isn't a line that is actually meant to work

2021-02-11 18:12 UTC, jaredlll08 commented on docs/Mods/Integration_Foregoing/WashingFactory.md
> +WashingFactory.add(String oreDictInput, ILiquidStack fluidInput, ILiquidStack fluidOutput);
Put this in a comment please, just so people know that it isn't a line that is actually meant to work

2021-02-11 18:12 UTC, jaredlll08 commented on docs/Mods/Integration_Foregoing/WashingFactory.md
> +WashingFactory.remove(String oreDictInput);
Put this in a comment please, just so people know that it isn't a line that is actually meant to work

2021-02-12 00:30 UTC, jaredlll08 commented
You commit didn't fix the issue, right now a user will just copy that code block and paste it into the script, and it isn't going to work.

Ideally it should look like:
```zenscript
// FermentationStation.add(ILiquidStack fluidInput, ILiquidStack fluidOutput);

FermentationStation.add(<liquid:lava> * 1, <liquid:pyrotheum> * 1);
```

So users can copy it, and know what param is what.

2021-02-12 07:29 UTC, JackyyTV commented
Sorry about that, should be fixed now.

2021-02-12 16:08 UTC, jaredlll08 commented
Thanks!

2021-02-12 16:08 UTC, merged