Add zensummoning documentation
CraftTweaker/CraftTweaker-Documentation pull request #427
Opened 2021-05-10 19:19 UTC by TeamDman

This is mostly autogenerated, and I'm not sure what else needs to be added for sidebar and i18n support.

2021-05-11 06:41 UTC, kindlich requested changes
Changes to docs.json missing.
You may want to move your stuff to `docs_exported` if they are only generated by the AP and have your example an extra file here 🤔 

@jaredlll08 what do you think?

2021-05-11 06:41 UTC, kindlich commented on docs/mods/zensummoning/MobInfo.md
> +MobInfo.create();
You could also just annotate the constructor with `@ZenCodeType.Constructor` 😉

2021-05-11 06:41 UTC, kindlich commented on docs/mods/zensummoning/MobInfo.md
> +| mob | string | resource location |
You can use MCEntityType here, for a bit more of type safety:
`myMobInfo.setMob(<entityType:minecraft:zombie_villager>)`

2021-05-11 15:39 UTC, jaredlll08 commented
As kindlich said, you can just move the generated files into like ```docs_exported/ZenSummoning``` and it should handle the rest of merging the docs.json file

2021-05-14 19:03 UTC, jaredlll08 commented
For the examples, can you just add a little "The following script will do: <explain what it does", just so people know what they are looking at.

Otherwise it looks great!

2021-05-15 00:36 UTC, jaredlll08 requested changes

2021-05-15 00:36 UTC, jaredlll08 commented on docs/mods/zensummoning/examples.md
> +- Consumes 1 stone, 12 eggs, 1 stick as catalyst
```suggestion
- Consumes 1 stone, 12 eggs and 1 stick as catalyst
```

2021-05-15 00:36 UTC, jaredlll08 commented on docs/mods/zensummoning/examples.md
> +    - https://minecraft.fandom.com/wiki/Attribute
```suggestion
    - [https://minecraft.fandom.com/wiki/Attribute](https://minecraft.fandom.com/wiki/Attribute)
```

2021-05-15 00:36 UTC, jaredlll08 commented on docs/mods/zensummoning/examples.md
> +- Consumes one sapling (with oredict support), consumes one stone as catalyst
```suggestion
- Consumes one sapling (with oredict support) and consumes one stone as catalyst
```

2021-05-15 00:36 UTC, jaredlll08 commented on docs/mods/zensummoning/examples.md
> +- Adds two summoning with same reagents an catalyst
```suggestion
- Adds two summoning with the same reagents an catalyst
```

2021-05-15 00:36 UTC, jaredlll08 commented on docs/mods/zensummoning/examples.md
> +- When attempted, there is a 4:1 chance that you will summon the cow.
```suggestion
- When attempted, there is a 4 in 1 chance that you will summon the cow.
```

2021-05-15 00:36 UTC, jaredlll08 commented on docs/mods/zensummoning/examples.md
> +- Consumes 1 stone, 12 eggs
```suggestion
- Consumes 1 stone and 12 eggs
```

2021-05-15 04:55 UTC, TeamDman commented on docs/mods/zensummoning/examples.md
> +- When attempted, there is a 4:1 chance that you will summon the cow.
Changed to `4 in 5`

2021-05-15 05:42 UTC, merged