Create Automated
CraftTweaker/CraftTweaker-Documentation pull request #457
Opened 2021-08-09 19:06 UTC by kotakotik22

Documentation for [CreateAutomated](https://www.curseforge.com/minecraft/mc-mods/create-automated)

- [X] Extracting recipes
- [ ] Picking recipes
- [ ] Drill head items

2021-08-09 19:27 UTC, jaredlll08 commented on docs/mods/Create/CreateAutomated/ExtractingRecipes.md
> +`maxOre` is optional. If not provided, `minOre` will be used which will create a recipe always giving the same amount of ore
```suggestion
`maxOre` is optional. If not provided, `minOre` will be used which will create a recipe always giving the same amount of ore.
```

2021-08-09 19:28 UTC, jaredlll08 requested changes

2021-08-09 19:28 UTC, jaredlll08 commented on docs/mods/Create/CreateAutomated/ExtractingRecipes.md
> +The progress builder makes your code more readable, with a builder that actually makes sense instead of some big number
```suggestion
The progress builder makes your code more readable, with a builder that actually makes sense instead of some big number.
```

2021-08-10 11:05 UTC, kotakotik22 commented
ill keep this as a draft for now because some of the crafttweaker features in the docs arent released yet

2021-08-10 18:07 UTC, kotakotik22 commented
version released on curseforge

2021-08-10 19:54 UTC, jaredlll08 requested changes

2021-08-10 19:54 UTC, jaredlll08 commented on docs/mods/CreateAutomated/DrillHeads.md
> +::requiredMod[Create Automated]{builtIn=true modLink=https://www.curseforge.com/minecraft/mc-mods/create-automated}
No idea what is going on here, but it should probably be

```suggestion
::requiredMod[Create Automated]{builtIn=true modLink=https://www.curseforge.com/minecraft/mc-mods/create-automated}
::requiredMod[Create Automated]{builtIn=false modLink=https://www.curseforge.com/minecraft/mc-mods/create-automated requiredMod=ContentTweaker requiredModLink=https://www.curseforge.com/minecraft/mc-mods/contenttweaker}
```

2021-08-10 19:54 UTC, jaredlll08 commented on docs/mods/CreateAutomated/DrillHeads.md
> +so you obtain it by calling [ItemBuilder](/mods/contenttweaker/API/item/ItemBuilder)#withType<DrillHeadBuilder>().
```suggestion
so you obtain it by calling [ItemBuilder](/mods/contenttweaker/API/item/ItemBuilder)#withType&lt;DrillHeadBuilder&gt;().
```

2021-08-11 22:53 UTC, merged