Add ZenCode tab, add applyFlight in ArmorSetEffects, start work on Preprocessors and advanced ZC things
CraftTweaker/CraftTweaker-Documentation pull request #495
Opened 2021-11-16 16:11 UTC by Witixin1512

I also moved the Arrays file there, let me know if you don't like that

2021-11-16 21:23 UTC, jaredlll08 requested changes

2021-11-16 21:23 UTC, jaredlll08 commented on docs/1.16/content/zencode/ConditionalCode.md
> +An if statement executed the piece of code if the `boolean` inside of its bracket evaluates to `true`.
```suggestion
An if statement executes the piece of code if the `boolean` inside of its bracket evaluates to `true`.
```

2021-11-16 21:23 UTC, jaredlll08 commented on docs/1.16/content/zencode/Preprocessors/Preprocessors.md
> +They run various actions on scripts. A preprocessor is called by appending `#preprocessorname [arguments]` to the top of your script. Be careful not to accidentally enable one through the use of a co
pre procs aren't always at the top, they can actually be anywhere, like the `#snip` preproc.

2021-11-16 21:40 UTC, Witixin1512 commented on docs/1.16/content/zencode/Preprocessors/Preprocessors.md
> +They run various actions on scripts. A preprocessor is called by appending `#preprocessorname [arguments]` to the top of your script. Be careful not to accidentally enable one through the use of a co
I actually forgot about the `#snip` preprocessor, that's gonna be annoying

2021-11-16 22:46 UTC, jaredlll08 commented on docs/1.16/content/zencode/Preprocessors/Preprocessors.md
> +They run various actions on scripts. A preprocessor is called by appending `#preprocessorname [arguments]` to the top of your script. Be careful not to accidentally enable one through the use of a co
There are actually quite a few:
```
#debug
#loader
#loadfirst
#loadlast
#modloaded
#noload
#priority
#replace
```

and snips:
```
#snip modloaded
#snip modnotloaded
#snip side
#snip start
#snip end
```

2021-11-16 23:32 UTC, Witixin1512 commented on docs/1.16/content/zencode/Preprocessors/Preprocessors.md
> +They run various actions on scripts. A preprocessor is called by appending `#preprocessorname [arguments]` to the top of your script. Be careful not to accidentally enable one through the use of a co
I thought I included a list with doc links with some of them in the prepocessors file...
I'm gonna double check that soon

2021-11-17 14:26 UTC, Witixin1512 commented on docs/1.16/content/zencode/Preprocessors/Preprocessors.md
> +They run various actions on scripts. A preprocessor is called by appending `#preprocessorname [arguments]` to the top of your script. Be careful not to accidentally enable one through the use of a co
Fixed that, added more preprocessors to the file, I'll look into what they do exactly. Was looking into this yesterday, I might ask you about some things (https://github.com/CraftTweaker/CraftTweaker/tree/1.16/src/main/java/com/blamejared/crafttweaker/api/zencode/impl/preprocessors)

I presume `noload` does what the name claims, `debug` generates classes, `loadfirst` and `loadlast` are direct changes to priority +-1? Or do they literally make the scripts load first or last depending on other's scripts priority? What does `replace` do? I _think_ I know what `snip` does, its a fragment of a script that only loads on X or Y side and if the conditions match. What if you want to combine params? Also, do you need to put the params next to the `start` call or are they on another line?) 

Just realised this is a lot of text so if you'd rather answer in discord go ahead lol
Thanks!

2021-11-17 19:31 UTC, jaredlll08 approved these changes

2021-11-17 21:05 UTC, merged