Docs for Immersive Intelligence mod (1.12.2)
CraftTweaker/CraftTweaker-Documentation pull request #503
Opened 2022-01-28 01:27 UTC by Pabilo8

2022-01-28 02:20 UTC, jaredlll08 requested changes

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Ammunition_Workshop.md
> +The `AmmunitionWorkshop` package can be used to add/remove recipes to/from the II Ammunition Workshop.
```suggestion
The `AmmunitionWorkshop` package can be used to modify the Immersive Intelligence Ammunition Workshop recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Ammunition_Workshop.md
> +IAmmunitionWorkshopFunction is a function used to determine the item outputted by a recipe based on ingredients.
```suggestion
IAmmunitionWorkshopFunction is a function used to determine the output item of a recipe based on its ingredients.    
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Ammunition_Workshop.md
> +It can be used i.e. to get core NBT tag or merge core and casing's NBT tags.
```suggestion
For example, It can be used to get the core NBT tag or merge the core and casing's NBT tags.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Block_Penetration_Values.md
> +Integrity is the amount of hitpoints a block has. Damage is dealt in similar way it is done to entities.
```suggestion
Integrity is the amount of hitpoints a block has. Damage is dealt in a similar way it is done to entities.  
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Bullet_System.md
> +The `Brightness` parameter is a value 0.0-1.0, determining the glow effect for Albedo (colored lighting mod) compat.
```suggestion
For the `Name` parameter use a simple material name, such as `dirt`, `iron` or `diamond`.  
The `Texture` parameter is a texture path (resource location) string, f.e. `"minecraft:textures/blocks/dirt"`.  
The `Damage` parameter is a damage value in half-hearts.  
The `Mass` parameter determines gravity, see [Common Ammunition Values]().  
The `Brightness` parameter is a value 0.0-1.0, determining the glow effect for Albedo (colored lighting mod) compat.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/CO2_Input.md
> +The `CO2Input` package can be used to add TileEntities, including Multiblocks to the II CO2 Collector sources list.
```suggestion
The `CO2Input` package can be used to add TileEntities, including Multiblocks to the Immersive Intelligence CO2 Collector sources list.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Chemical_Bath.md
> +The `ChemicalBath` package can be used to add/remove recipes to/from the II Chemical Bath.
```suggestion
The `ChemicalBath` package can be used to modify the Immersive Intelligence Chemical Bath recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Chemical_Painter.md
> +The `ChemicalPainter` package can be used to add/remove recipes to/from the II Chemical Painter.
```suggestion
The `ChemicalPainter` package can be used to modify the Immersive Intelligence Chemical Painter recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Chemical_Painter.md
> +color.
```suggestion
Paint amount is the total amount of ink in mB used for a single process.  
Amounts of specific ink are based on their percentage in the [CMYK](https://en.wikipedia.org/wiki/CMYK_color_model)
color model.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Chemical_Painter.md
> +IChemicalPainterFunction is a function used to determine the item outputted by a recipe based on the stack and selected
```suggestion
IChemicalPainterFunction is a function used to determine the output item of a recipe based on the stack and selected
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Chemical_Painter.md
> +It can be used i.e. to get core NBT tag or merge core and casing's NBT tags.
```suggestion
For example, it can be used to get the core NBT tag or merge the core and casing's NBT tags.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Rotary_Input.md
> +The `RotaryInput` package can be used to make a Tile Entity supported by II Transmission Box.
```suggestion
The `RotaryInput` package can be used to make a Tile Entity supported by the Immersive Intelligence Transmission Box.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Rotary_Input.md
> +For default torque values, check IIconfig file for `dynamo_windmill_torque` and `dynamo_watermill_torque`.
I would like this to say something like "check the Immersive Intelligence config file", but if the file is called `IIconfig` then that is fine.

I just want it to be clear to users what they should be looking for.

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Coagulator.md
> +The `Coagulator` package can be used to add/remove recipes to/from the II Coagulator.
```suggestion
The `Coagulator` package can be used to modify the Immersive Intelligence Coagulator recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Electrolyzer.md
> +The `Electrolyzer` package can be used to add/remove recipes to/from the II Electrolyzer.
```suggestion
The `Electrolyzer` package can be used to modify the Immersive Intelligence Electrolyzer recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Electrolyzer.md
> +Latex and Rubber texture are texture path (resource location) strings, f.e. `"immersiveintelligence:textures/blocks/multiblock/Electrolyzer/latex_strip.png"`.
```suggestion
Latex and Rubber texture are texture path (resource location) strings, i.e. `"immersiveintelligence:textures/blocks/multiblock/Electrolyzer/latex_strip.png"`.  
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Filler.md
> +The `Filler` package can be used to add/remove recipes to/from the II Filler.
```suggestion
The `Filler` package can be used to modify the Immersive Intelligence Filler recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Fuel_Station.md
> +The `FuelStation` package can be used to add/remove recipes to/from the II Fuel Station.
```suggestion
The `FuelStation` package can be used to modify the Immersive Intelligence Fuel Station recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Lighter_Fuels.md
> +The `LighterFuels` package can be used to add/remove II Engineer's Lighter Fuels.
```suggestion
The `LighterFuels` package can be used to modify the Immersive Intelligence Engineer's Lighter Fuels.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Machinegun.md
> +The `Machinegun` package can be used to tweak coolant fluids accepted by the II Machinegun.
```suggestion
The `Machinegun` package can be used to tweak coolant fluids accepted by the Immersive Intelligence Machinegun.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Machinegun.md
> +The methods accept the same parameters, but they serve different purpose.
```suggestion
The methods accept the same parameters, but they serve different purposes.  
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Precision_Assembler.md
> +The `PrecisionAssembler` package can be used to add/remove recipes to/from the II Precision Assembler.
```suggestion
The `PrecisionAssembler` package can be used to modify the Immersive Intelligence Precision Assembler recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Precision_Assembler.md
> +Note the work/pick/drop times are dependent on the tool itself. Tool use durations can be modified using the II config
As I said before, please make this clearer as to what file they should be looking at.

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Sawmill.md
> +The `Sawmill` package can be used to add/remove recipes to/from the II Sawmill.
```suggestion
The `Sawmill` package can be used to modify the Immersive Intelligence Sawmill recipes.
```

2022-01-28 02:20 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Vulcanizer.md
> +The `Vulcanizer` package can be used to add/remove recipes to/from the II Vulcanizer.
```suggestion
The `Vulcanizer` package can be used to modify the Immersive Intelligence Vulcanizer recipes.
```

2022-01-28 14:13 UTC, Pabilo8 commented on docs/1.12/docs.json
> +      "Immersive Intelligence": {
Fixed in a6ab2bd

2022-01-28 14:13 UTC, Pabilo8 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Precision_Assembler.md
> +Note the work/pick/drop times are dependent on the tool itself. Tool use durations can be modified using the II config
Fixed in a6ab2bd

2022-01-29 17:22 UTC, jaredlll08 requested changes

2022-01-29 17:22 UTC, jaredlll08 commented on docs/1.12/content/Mods/Immersive_Intelligence/CraftTweaker_Support/Precision_Assembler.md
> +Note the work/pick/drop times are dependent on the tool itself. Tool use durations can be modified in `tools` section of `config/immersiveintelligence.cfg` file.
```suggestion
Note the work/pick/drop times are dependent on the tool itself. Tool use durations can be modified in `tools` section of the `config/immersiveintelligence.cfg` file.  
```

2022-01-29 17:22 UTC, merged

2022-01-30 13:17 UTC, Pabilo8 commented
I noticed the docs can no longer build after you merged my PR. 
I also noticed that (most likely caused by intellij auto-formatting the document) the first line of some files
`::requiredMod[Immersive Intelligence]{builtIn=true modLink=https://www.curseforge.com/minecraft/mc-mods/immersive-intelligence}`
split into 2
Do you think it might be the reason? If so, I'll fix it.

2022-01-30 19:36 UTC, jaredlll08 commented
You didn't break it, it was something else and I fixed the line break