Add SixikUtils Docs
CraftTweaker/CraftTweaker-Documentation pull request #547
Opened 2023-06-30 08:52 UTC by 8sixik

2023-08-03 20:56 UTC, Witixin1512 requested changes
Requires a couple of changes. I'd prefer it if there were a lot more comments on methods that are not immediately obvious to anyone who doesn't have the source at hand, as well as better naming of methods and parameters. Some methods have parameters with no name and explanation, especially booleans.

2023-08-04 16:02 UTC, 8sixik commented on docs_exported/1.19/sixikutils/docs/mods/sixikutils/curios/player/Player.md
> +import crafttweaker.api.entity.type.player.Player;
In the title?

2023-08-04 16:04 UTC, 8sixik commented on docs_exported/1.19/sixikutils/docs/mods/sixikutils/ftbquest/events/ChapterStartedEvent.md
> +myChapterStartedEvent.getObject();
GetObject is the quest ID, and get Chapter gets the Chapter ID directly

2023-08-04 16:17 UTC, Witixin1512 commented on docs_exported/1.19/sixikutils/docs/mods/sixikutils/curios/player/Player.md
> +import crafttweaker.api.entity.type.player.Player;
Yes, see how CraftTweaker does it for Tags for example.

2023-08-09 15:48 UTC, Witixin1512 requested changes
A lot of things have improved, but there's a couple of minor changes required: Like invalid classes or typos.
Also double check the previous review, as there are some things that still aren't done from that.

2023-08-09 15:48 UTC, Witixin1512 commented on docs_exported/1.19/sixikutils/docs/mods/sixikutils/utils/events/entity/player/PlayerBeforeLoadedChunkEvent.md
> +
Same as for the After Event

2023-08-25 08:52 UTC, 8sixik commented
I decided I'd better rewrite everything. Because when I made this mod and wiki, I didn't know anything about java and because of this there is a lot of confusion.

2023-08-25 08:52 UTC, closed without merging