1.12.2: Restructuring events & some fixes
CraftTweaker/CraftTweaker-Documentation pull request #572
Opened 2024-04-14 21:35 UTC by sora7672

The small fixes are from other discord members or i found while building my example repo for 1.12.2.
They were from 5th-11th april.
After that i basically changed all event pages, so they have the same buildup.
(because i worked sometimes to long, i created some errors which i fixed later on, thats why sometimes 3 chanegs are at the same file)

With this it should be easyer to follow for no programmers to follow where they find stuff.

I hope its fine for you like this too :)

2024-04-14 22:28 UTC, jaredlll08 requested changes
Thanks for this!

Just a *few* things need changing

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerSetSpawn.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerUseHoe.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerUseItemStart.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerUseItemTick.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PortalSpawn.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PotionBrewPre.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/ProjectileImpactArrow.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/ProjectileImpactFireball.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/ProjectileImpactThrowable.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
```suggestion
- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop something from happening
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerCrafted.md
> +Which to be more precise, the player takes out the result, not changing smth. in the grid.
```suggestion
Which to be more precise, the player takes out the result, not changing something in the grid.
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/CriticalHit.md
> +| `player`        |                 | [IBlockPos](/Vanilla/Player/IPlayer/)             |
```suggestion
| `player`        |                 | [IPlayer](/Vanilla/Player/IPlayer/)             |
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerSleepInBed.md
> +`NOT_POSSIBLE_HERE`, `NOT_POSSIBLE_NOW`, `NOT_SAFE`, `OK` or  `OTHER_PROBLEM`
```suggestion
`NOT_POSSIBLE_HERE`, `NOT_POSSIBLE_NOW`, `NOT_SAFE`, `OK` or `OTHER_PROBLEM`
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerRightClickItem.md
> +- [IHasCancellationResult] (no doc page so far)
```suggestion
- IHasCancellationResult
```
If it doesn't have a page, rather don't link, compared to linking to a 404

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/IPlayerEvent.md
> +The  [IPlayer](/Vanilla/Players/IPlayer/)  is an extension of the class [IEntityLivingBase](/Vanilla/Entities/IEntityLivingBase/) ,
```suggestion
The [IPlayer](/Vanilla/Players/IPlayer/) is an extension of the class [IEntityLivingBase](/Vanilla/Entities/IEntityLivingBase/) ,
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/IPlayerEvent.md
> +thus with `event.player` you have access to all  ZenGetters/ZenSetters from [IEntityLivingBase](/Vanilla/Entities/IEntityLivingBase/) allready.
```suggestion
thus with `event.player` you have access to all  ZenGetters/ZenSetters from [IEntityLivingBase](/Vanilla/Entities/IEntityLivingBase/) already.
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerDeathDrops.md
> +| `items`         |  `items`        | [`List<IEntityItem>`](/Vanilla/Entities/IEntityItem/) |
```suggestion
| `items`         |  `items`        | List<[IEntityItem](/Vanilla/Entities/IEntityItem/)> |
```

2024-04-14 22:28 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/PlayerInteractBlock.md
> +- [IHasCancellationResult] (No doc for it till now)
```suggestion
- IHasCancellationResult
```

2024-04-15 07:37 UTC, sora7672 commented on docs/1.12/content/Vanilla/Events/Events/AnimalTame.md
> +- `event.cancel();` Method, returns void (nothing). Can cancel the event and stop smth. from happening
Sure, will do. But anywhen later this week. IRL a lil more this week :D

2024-04-15 07:41 UTC, sora7672 commented on docs/1.12/content/Vanilla/Events/Events/BlockNeighborNotify.md
> +| `notifiedSides` |                 | [IFacing](/Vanilla/World/IFacing) [ ]              |
Intended with the space between. Better readability on some devices/browsers. Soke show it like a block, which could be confusing

2024-04-15 07:45 UTC, jaredlll08 commented on docs/1.12/content/Vanilla/Events/Events/BlockNeighborNotify.md
> +| `notifiedSides` |                 | [IFacing](/Vanilla/World/IFacing) [ ]              |
I can't imagine that any modern browser would change how plaintext is rendered like that, do you have an example of where it messes up?

2024-04-15 08:47 UTC, sora7672 commented on docs/1.12/content/Vanilla/Events/Events/BlockNeighborNotify.md
> +| `notifiedSides` |                 | [IFacing](/Vanilla/World/IFacing) [ ]              |
![grafik](https://github.com/CraftTweaker/CraftTweaker-Documentation/assets/7255402/cecee9f9-d1c5-4062-b690-106a209b471a)

Looking like this. 
Easyer to read with sapce. But changed all allready ;)
just so you see what i mean with difference.

2024-04-15 20:53 UTC, jaredlll08 approved these changes

2024-04-15 20:53 UTC, merged